In [64]:
import pandas as pd

In [65]:
data=pd.read_parquet("../data/colors.parquet","pyarrow")

In [66]:
data.head()

,Color Name,HEX Code,Category,Description,Emotion,Personality,Mood,Symbolism,Use Case,Keywords,R,G,B,Hue,Saturation,Lightness,Contrast Level
0,Deep Maroon,#D62559,Red Family (Ruby Red),A vibrant and deep shade of maroon.,"Passionate, Intense","Bold, Dramatic","Strong, Powerful","Deep Maroon often symbolizes power, strength, ...",Ideal for creating a striking impact in design...,"Powerful, Passionate, Bold, Deep, Strong, Inte...",214,37,89,342.37,70.52,49.22,Dark
1,Golden Brick,#E5B262,"Warm, Earthy",A warm and inviting shade of golden brown.,"Comfort, Warmth, Optimism","Reliable, Friendly, Approachable","Cozy, Sunlit, Nurturing","Growth, Stability, Harvest",Ideal for creating a warm and inviting atmosph...,"Warm, Golden, Brown, Earthy, Comfortable, Cozy...",229,178,98,36.64,71.58,64.12,Dark
2,Lime Green,#8CCD48,"Bright, Vibrant",A lively shade of green with yellow undertones.,"Energetic, Fresh","Outgoing, Adventurous","Playful, Exciting","Growth, Renewal, Envy (in some cultures)","Ideal for modern design elements, branding for...","Bright, Vibrant, Fresh, Energy, Nature, Green,...",140,205,72,89.32,57.08,54.31,Dark
3,Sage Green #356A40,#356A40,Green,"A rich, muted green shade with a hint of blue.",Calmness and Relaxation,"Stable and reliable, like an old friend.",Serene and earthy.,"Growth, harmony, and balance in nature.",Ideal for spaces promoting relaxation and tran...,"Calm, Earthy, Nature, Reliable, Stable.",53,106,64,132.45,33.33,31.18,Dark
4,Deep Sapphire Blue,#0618DE,"Dark, Intense","A vibrant and rich shade of blue, reminiscent ...","Serene, Luxurious","Majestic, Mysterious","Calm, Elegant","Deep Sapphire Blue often symbolizes wisdom, lo...","Ideal for branding luxury items, technology, o...","Luxurious, Deep, Ocean, Premium, Elegant, Myst...",6,24,222,235.00,94.74,44.71,Dark

In [67]:
def get_hue_family(h, s, l):
    if s < 10:
        return "neutral"
    if 15 <= h <= 45 and s <= 60 and l <= 55:
        return "brown"
    if h < 15 or h >= 345:
        return "red"
    elif h < 45:
        return "orange"
    elif h < 70:
        return "yellow"
    elif h < 170:
        return "green"
    elif h < 200:
        return "cyan"
    elif h < 260:
        return "blue"
    elif h < 300:
        return "purple"
    elif h < 345:
        return "pink"

data["hue_family"] = data.apply(
    lambda row: get_hue_family(row["Hue"], row["Saturation"], row["Lightness"]),
    axis=1
)

In [68]:
data.head()

,Color Name,HEX Code,Category,Description,Emotion,Personality,Mood,Symbolism,Use Case,Keywords,R,G,B,Hue,Saturation,Lightness,Contrast Level,hue_family
0,Deep Maroon,#D62559,Red Family (Ruby Red),A vibrant and deep shade of maroon.,"Passionate, Intense","Bold, Dramatic","Strong, Powerful","Deep Maroon often symbolizes power, strength, ...",Ideal for creating a striking impact in design...,"Powerful, Passionate, Bold, Deep, Strong, Inte...",214,37,89,342.37,70.52,49.22,Dark,pink
1,Golden Brick,#E5B262,"Warm, Earthy",A warm and inviting shade of golden brown.,"Comfort, Warmth, Optimism","Reliable, Friendly, Approachable","Cozy, Sunlit, Nurturing","Growth, Stability, Harvest",Ideal for creating a warm and inviting atmosph...,"Warm, Golden, Brown, Earthy, Comfortable, Cozy...",229,178,98,36.64,71.58,64.12,Dark,orange
2,Lime Green,#8CCD48,"Bright, Vibrant",A lively shade of green with yellow undertones.,"Energetic, Fresh","Outgoing, Adventurous","Playful, Exciting","Growth, Renewal, Envy (in some cultures)","Ideal for modern design elements, branding for...","Bright, Vibrant, Fresh, Energy, Nature, Green,...",140,205,72,89.32,57.08,54.31,Dark,green
3,Sage Green #356A40,#356A40,Green,"A rich, muted green shade with a hint of blue.",Calmness and Relaxation,"Stable and reliable, like an old friend.",Serene and earthy.,"Growth, harmony, and balance in nature.",Ideal for spaces promoting relaxation and tran...,"Calm, Earthy, Nature, Reliable, Stable.",53,106,64,132.45,33.33,31.18,Dark,green
4,Deep Sapphire Blue,#0618DE,"Dark, Intense","A vibrant and rich shade of blue, reminiscent ...","Serene, Luxurious","Majestic, Mysterious","Calm, Elegant","Deep Sapphire Blue often symbolizes wisdom, lo...","Ideal for branding luxury items, technology, o...","Luxurious, Deep, Ocean, Premium, Elegant, Myst...",6,24,222,235.00,94.74,44.71,Dark,blue

In [69]:
import re

def normalize_text(text):
    if pd.isna(text):
        return text
    return re.sub(r"[^\w\s]", "", text.lower())

In [70]:
data.columns

Index(['Color Name', 'HEX Code', 'Category', 'Description', 'Emotion',
       'Personality', 'Mood', 'Symbolism', 'Use Case', 'Keywords', 'R', 'G',
       'B', 'Hue', 'Saturation', 'Lightness', 'Contrast Level', 'hue_family'],
      dtype='str')

In [71]:
exclude = [
    "HEX Code", "Keywords", "R", "G", "B",
    "Hue", "Saturation", "Lightness"
]

columns = [col for col in data.columns if col not in exclude]

data[columns] = data[columns].apply(lambda col: col.map(normalize_text))

In [72]:
data.head()

,Color Name,HEX Code,Category,Description,Emotion,Personality,Mood,Symbolism,Use Case,Keywords,R,G,B,Hue,Saturation,Lightness,Contrast Level,hue_family
0,deep maroon,#D62559,red family ruby red,a vibrant and deep shade of maroon,passionate intense,bold dramatic,strong powerful,deep maroon often symbolizes power strength co...,ideal for creating a striking impact in design...,"Powerful, Passionate, Bold, Deep, Strong, Inte...",214,37,89,342.37,70.52,49.22,dark,pink
1,golden brick,#E5B262,warm earthy,a warm and inviting shade of golden brown,comfort warmth optimism,reliable friendly approachable,cozy sunlit nurturing,growth stability harvest,ideal for creating a warm and inviting atmosph...,"Warm, Golden, Brown, Earthy, Comfortable, Cozy...",229,178,98,36.64,71.58,64.12,dark,orange
2,lime green,#8CCD48,bright vibrant,a lively shade of green with yellow undertones,energetic fresh,outgoing adventurous,playful exciting,growth renewal envy in some cultures,ideal for modern design elements branding for ...,"Bright, Vibrant, Fresh, Energy, Nature, Green,...",140,205,72,89.32,57.08,54.31,dark,green
3,sage green 356a40,#356A40,green,a rich muted green shade with a hint of blue,calmness and relaxation,stable and reliable like an old friend,serene and earthy,growth harmony and balance in nature,ideal for spaces promoting relaxation and tran...,"Calm, Earthy, Nature, Reliable, Stable.",53,106,64,132.45,33.33,31.18,dark,green
4,deep sapphire blue,#0618DE,dark intense,a vibrant and rich shade of blue reminiscent o...,serene luxurious,majestic mysterious,calm elegant,deep sapphire blue often symbolizes wisdom loy...,ideal for branding luxury items technology or ...,"Luxurious, Deep, Ocean, Premium, Elegant, Myst...",6,24,222,235.00,94.74,44.71,dark,blue

In [73]:
data["Keywords"] = data["Keywords"].apply(
    lambda x: [word.strip().lower() for word in x.split(",")] 
    if isinstance(x, str) else []
)

In [74]:
data.head()

,Color Name,HEX Code,Category,Description,Emotion,Personality,Mood,Symbolism,Use Case,Keywords,R,G,B,Hue,Saturation,Lightness,Contrast Level,hue_family
0,deep maroon,#D62559,red family ruby red,a vibrant and deep shade of maroon,passionate intense,bold dramatic,strong powerful,deep maroon often symbolizes power strength co...,ideal for creating a striking impact in design...,"[powerful, passionate, bold, deep, strong, int...",214,37,89,342.37,70.52,49.22,dark,pink
1,golden brick,#E5B262,warm earthy,a warm and inviting shade of golden brown,comfort warmth optimism,reliable friendly approachable,cozy sunlit nurturing,growth stability harvest,ideal for creating a warm and inviting atmosph...,"[warm, golden, brown, earthy, comfortable, coz...",229,178,98,36.64,71.58,64.12,dark,orange
2,lime green,#8CCD48,bright vibrant,a lively shade of green with yellow undertones,energetic fresh,outgoing adventurous,playful exciting,growth renewal envy in some cultures,ideal for modern design elements branding for ...,"[bright, vibrant, fresh, energy, nature, green...",140,205,72,89.32,57.08,54.31,dark,green
3,sage green 356a40,#356A40,green,a rich muted green shade with a hint of blue,calmness and relaxation,stable and reliable like an old friend,serene and earthy,growth harmony and balance in nature,ideal for spaces promoting relaxation and tran...,"[calm, earthy, nature, reliable, stable.]",53,106,64,132.45,33.33,31.18,dark,green
4,deep sapphire blue,#0618DE,dark intense,a vibrant and rich shade of blue reminiscent o...,serene luxurious,majestic mysterious,calm elegant,deep sapphire blue often symbolizes wisdom loy...,ideal for branding luxury items technology or ...,"[luxurious, deep, ocean, premium, elegant, mys...",6,24,222,235.00,94.74,44.71,dark,blue

In [75]:
data.columns

Index(['Color Name', 'HEX Code', 'Category', 'Description', 'Emotion',
       'Personality', 'Mood', 'Symbolism', 'Use Case', 'Keywords', 'R', 'G',
       'B', 'Hue', 'Saturation', 'Lightness', 'Contrast Level', 'hue_family'],
      dtype='str')

In [76]:
data["search_text"]=data["Category"]+" "+data["Description"]+" "+data["Emotion"]+" "+data["Personality"]+" "+data["Mood"]+" "+data["Symbolism"]+" "+data["Use Case"]+" "+data["hue_family"]

In [77]:
data=data.drop(columns=['Description', 'Emotion',
       'Personality', 'Mood', 'Symbolism', 'Use Case','R', 'G',
       'B', 'Hue', 'Saturation', 'Lightness', 'Contrast Level'])

In [78]:
data.dropna(inplace=True)

In [79]:
data=data.rename(columns={
    "Color Name":'color_name',
    'HEX Code':'hex',
    'Category':'category',
    'Keywords':'keywords'
})

In [80]:
import matplotlib.colors as mcolors

data["rgb"] = data["hex"].apply(
    lambda x: tuple(int(c * 255) for c in mcolors.to_rgb(x))
)

In [81]:
import colorsys

def hex_to_hsl(hex_code):
    hex_code = hex_code.lstrip("#")
    r, g, b = [int(hex_code[i:i+2], 16) / 255 for i in (0, 2, 4)]

    h, l, s = colorsys.rgb_to_hls(r, g, b)

    return (round(h * 360), round(s * 100), round(l * 100))

data["hsl"] = data["hex"].apply(hex_to_hsl)

In [82]:
data.head()

,color_name,hex,category,keywords,hue_family,search_text,rgb,hsl
0,deep maroon,#D62559,red family ruby red,"[powerful, passionate, bold, deep, strong, int...",pink,red family ruby red a vibrant and deep shade o...,"(214, 37, 89)","(342, 71, 49)"
1,golden brick,#E5B262,warm earthy,"[warm, golden, brown, earthy, comfortable, coz...",orange,warm earthy a warm and inviting shade of golde...,"(229, 178, 98)","(37, 72, 64)"
2,lime green,#8CCD48,bright vibrant,"[bright, vibrant, fresh, energy, nature, green...",green,bright vibrant a lively shade of green with ye...,"(140, 205, 72)","(89, 57, 54)"
3,sage green 356a40,#356A40,green,"[calm, earthy, nature, reliable, stable.]",green,green a rich muted green shade with a hint of ...,"(53, 106, 64)","(132, 33, 31)"
4,deep sapphire blue,#0618DE,dark intense,"[luxurious, deep, ocean, premium, elegant, mys...",blue,dark intense a vibrant and rich shade of blue ...,"(6, 24, 222)","(235, 95, 45)"

In [83]:
def get_brightness(r, g, b):
    # Normalize RGB
    r, g, b = r / 255, g / 255, b / 255

    # sRGB → linear RGB
    def linear(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = map(linear, (r, g, b))

    # Relative luminance
    luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b

    if luminance >= 0.7:
        return "bright"
    elif luminance <= 0.25:
        return "dark"
    else:
        return "medium"

In [84]:
data["brightness"] = data["rgb"].apply(
    lambda rgb: get_brightness(*rgb)
)

In [85]:
def get_warmth(r, g, b):
    warm_score = r - b

    if warm_score > 40:
        return "warm"
    elif warm_score < -40:
        return "cool"
    else:
        return "neutral"

In [86]:
data["warmth"] = data["rgb"].apply(
    lambda rgb: get_warmth(*rgb)
)

In [87]:
def contrast_score(r, g, b):
    r, g, b = r / 255, g / 255, b / 255

    def linear(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = map(linear, (r, g, b))

    luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b

    contrast_white = 1.05 / (luminance + 0.05)
    contrast_black = (luminance + 0.05) / 0.05

    return round(max(contrast_white, contrast_black), 2)

In [88]:
data["contrast_score"] = data["rgb"].apply(
    lambda rgb: contrast_score(*rgb)
)

In [89]:
def get_color_style(h, s, l):
    styles = []

    # Pastel
    if s >= 20 and s <= 60 and l >= 70:
        styles.append("pastel")

    # Vibrant
    if s >= 70 and l >= 40 and l <= 65:
        styles.append("vibrant")

    # Muted
    if s < 40 and l >= 30 and l <= 70:
        styles.append("muted")

    # Deep
    if l < 30 and s >= 40:
        styles.append("deep")

    # Bright
    if l >= 75 and s >= 40:
        styles.append("bright")

    # Soft
    if s < 50 and l >= 60:
        styles.append("soft")

    # Bold
    if s >= 75:
        styles.append("bold")

    return styles

In [90]:
data["color_style"] = data['hsl'].apply(
    lambda hsl: get_color_style(
        *hsl
    ),
)

In [91]:
data

,color_name,hex,category,keywords,hue_family,search_text,rgb,hsl,brightness,warmth,contrast_score,color_style
0,deep maroon,#D62559,red family ruby red,"[powerful, passionate, bold, deep, strong, int...",pink,red family ruby red a vibrant and deep shade o...,"(214, 37, 89)","(342, 71, 49)",dark,warm,4.92,[vibrant]
1,golden brick,#E5B262,warm earthy,"[warm, golden, brown, earthy, comfortable, coz...",orange,warm earthy a warm and inviting shade of golde...,"(229, 178, 98)","(37, 72, 64)",medium,warm,10.88,[vibrant]
2,lime green,#8CCD48,bright vibrant,"[bright, vibrant, fresh, energy, nature, green...",green,bright vibrant a lively shade of green with ye...,"(140, 205, 72)","(89, 57, 54)",medium,warm,10.94,[]
3,sage green 356a40,#356A40,green,"[calm, earthy, nature, reliable, stable.]",green,green a rich muted green shade with a hint of ...,"(53, 106, 64)","(132, 33, 31)",dark,neutral,6.39,[muted]
4,deep sapphire blue,#0618DE,dark intense,"[luxurious, deep, ocean, premium, elegant, mys...",blue,dark intense a vibrant and rich shade of blue ...,"(6, 24, 222)","(235, 95, 45)",dark,cool,9.58,"[vibrant, bold]"
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,golden apricot,#D4A35C,pastel warm,"[warm, earthy, apricot, golden, pastel, autumn...",orange,pastel warm a rich and earthy blend of apricot...,"(212, 163, 92)","(35, 58, 60)",medium,warm,9.19,[]
99996,greenyellow spring yellow,#98F11F,secondary,"[vibrant, energy, nature, freshness, growth, s...",green,secondary a lively vibrant shade that is a ble...,"(152, 241, 31)","(85, 88, 53)",medium,warm,14.94,"[vibrant, bold]"
99997,medium purpleblue,#A49BD5,pastel,"[purple, pastel, blue, tranquil, dreamy, myste...",blue,pastel a medium shade of purple with a hint of...,"(164, 155, 213)","(249, 41, 72)",medium,cool,8.23,"[pastel, soft]"
99998,deep lavender mauve,#9F1CC5,purple pastel,"[lavender, mauve, purple, pastel, deep, rich, ...",purple,purple pastel a deep rich shade of lavender wi...,"(159, 28, 197)","(287, 75, 44)",dark,neutral,6.09,"[vibrant, bold]"
99999,rose brown,#EF9B9B,pastel neutral,"[warm, soft, pinkish brown, neutral, cozy, inv...",red,pastel neutral a soft warm shade of pinkish br...,"(239, 155, 155)","(0, 72, 77)",medium,warm,9.83,[bright]

In [92]:

data["color_id"] = data.index

In [93]:
data[data["search_text"].isna()==True]

Empty DataFrame
Columns: [color_name, hex, category, keywords, hue_family, search_text, rgb, hsl, brightness, warmth, contrast_score, color_style, color_id]
Index: []

In [95]:
data.to_parquet("../data/cleaned-colors.parquet",engine="pyarrow",index=False)